export const authActionTypes = {
  SEND_TOKEN_START: "SEND_TOKEN_START",
  SEND_TOKEN_SUCCESS: "SEND_TOKEN_SUCCESS",
  SEND_TOKEN_FAILURE: "SEND_TOKEN_FAILURE",
  REGISTER_USER_START: "REGISTER_USER_START",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
  LOG_USER_START: "LOG_USER_START",
  LOG_USER_SUCCESS: "LOG_USER_SUCCESS",
  LOG_USER_FAILURE: "LOG_USER_FAILURE",
}
